server:
  error:
    include-message: always             # Since the Spring Boot 2.3 release, error messages are no longer included in the server’s responses by default.

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: testDB                  # Sets the database that your Spring Boot application will interact with.

      authentication-database: admin    # Sets the authentication database. MongoDB has a default database for it, which name is admin.
      username: testUserName            # Username to login to mongoDB.
      password: testPassword            # Password to login to mongoDB.

      # OR

      # uri: mongodb://testUserName:testPassword@localhost:27017/admin